### ISSUE TITLE
Settings Update

### ISSUE THREAD

**Issue by jhewebdev** [MaikFischer/TeamPentagon#18]
**Update des Settings-Tabs und Implementierung von neuen Einstellmöglichkeiten**

## Tasks:

- [x]  UI Darstellung ändern (neues Tab System)
   - General Tab
   - Saves Tab
   - Themes

### General Tab (@VapeZ2k):
- [x] Audio Optionen hinzufügen (Lautstärkeregler für Musik und Soundeffekte)

### Saves Tab (@MaikFischer):
- [x] Speicherplatzinformationen anzeigen (gespeicherter Score, CPS und CPC)

### Theme Tab (@MrBengel):

- [x] Neue Anordnung der Elemente
