### ISSUE TITLE
Shop Fertigstellen

### ISSUE THREAD

**Issue by jhewebdev** [MaikFischer/TeamPentagon#6]
Fertigstellung des Shops. (GUI + Volle Funktionsfähigkeit)

**_Tasks:_**

- Hinzufügen und Initialisierung von allen Items
- Logic für jedes Item anwenden (siehe Issue #4 )
- Testen und bei Bedarf Probleme beheben

**Comment by jhewebdev** [comment]
### Ayo wollte mal kurz alles auflisten, was sich alles durch 2fcbd59e150056afa70249633a7b2731b751341c verändert hat:

### **Geplant/Erwartet:**

- [x] Alle Items sind jetzt kaufbar und alle ihrer Funktionen/Boni funktionieren
- [x] Das Credits-Pro-Sekunde Feature läuft jetzt wunderbar und hat nach einigem hin- und her auch keine Probleme mehr gemacht

### **Neu/Ideen, welche ich für sinnvoll hielt lol**

- [x] Jedes mal wenn der Spieler ein Item kauft steigt dessen Kaufpreis um 25%
- [x] Preise wurden angepasst (Die Preise waren einfach zu hoch und ich habe sie deshalb ein wenig angepasst aber muss ja nicht final sein ^^)
- [x] Das MouseDownEvent auf der ClickArea hat eine Abfrage für die Maustaste bekommen, damit der Score nur steigt, wenn der Spieler die linke Maustaste drückt (vorher konnte man beide drücken)

### **Was wir noch brauchen:**

Eigentlich nur noch die Bilder/Icons für die restlichen Items. Danach wäre der Shop erstmal fürs nächste Release fertig. 
Ich bitte euch dennoch mal alles bei euch zu testen um sicherzugehen, dass ich nichts übersehen habe 👍

**Comment by jhewebdev** [comment]
### Habe nochmal was am Shop geändert a38b18f576b6d903f7be9b961ec044a6344ec88e:

### Neu:

- [x] Der Preis auf den Buy-Buttons (z.B. $150) ist nun rot, solange der Spieler nicht die nötigen Credits zum Kaufen besitzt und wechselt zu Grün, sobald der Spieler genügend Credits besitzt. 
- [x] Sound Effekte auf den Shop Buttons (sowie auf allen anderen Buttons im Spiel: siehe #9 )

**Comment by jhewebdev** [comment]
### Letzte Änderungen vor Release 712c0b5c1f9da51e534fc54555c200e366b045c1:

- [x] Bugfix: Ein Fehler wurde behoben, welcher auftrat wenn der Spieler den Shop manuell schließt und wieder öffnet
- [x] Game Logic wurde bearbeitet, um einen saubereren Anstieg an Score zu ermöglichen (Score wird nun 10x so oft im UI aktualisiert)

Ich suche jetzt nochmal nach Bilder/Icons für die restlichen Items und dann können wir releasen 👍
